openapi: 3.1.0

info:
  title: Mindwm API
  description: API defining the operations available in the Mindwm API
  version: 0.1.0
servers:
  - url: "https://mindwmw.io/v1"
    description: Production API endpoint for the Mindwm API
