openapi: '3.1.0'
info:
  title: Mindwm API
  description: This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
  version: '0.1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  $ref: ./servers.json
components:
  schemas:
    CloudEvent:
      $ref: ./cloudevents.json
      discrimniator: type
    Clipboard:
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - properties:
            type:
              type: string
              const: Clipboard
              defaullt: Clipboard
            subject:
              type: string
              const: Clipboard
              defaullt: Clipboard
            source:
              type: string
              pattern: mindwm.[a-zA-Z0-9_][a-zA-Z0-9_-]{0,31}\\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-).clipboard$
            data:
              $ref: '#/components/schemas/ClipboardPayload'
      additionalProperties: false
      examples:
        - source: mindwm.alice.laptop.clipboard
          subject: Clipboard
          type: Clipboard
          id: d0c13e76-3f79-11ef-8f1d-4be6bb85b216
          specversion: '1.0.0'
          data:
            $ref: '#/components/schemas/ClipboardPayload/examples/0'
    ClipboardPayload:
      type: object
      properties:
        start:
          type: array
          description: Starting position of clipboard selection [x,y]
          items:
            type: integer
          minItems: 2
          maxItems: 2
        stop:
          type: array
          description: Ending position of clipboard selection [x,y]
          items:
            type: integer
          minItems: 2
          maxItems: 2
        data:
          type: string
          description: Clipboard data
          minLength: 1
        type:
          type: string
          description: Clipboard type
          enum:
            - primary
            - secondary
            - clipboard
        context:
          type: object
          description: Selection context
          properties:
            window:
              type: string
              description: window id
      examples:
        - data: clipboard selection data
          type: primary
          start:
            - 86
            - 120
          stop:
            - 321
            - 420
          context:
            window: '0x8061cdef'
    TmuxPaneIoDocument:
      type: object
      properties:
        input:
          type: string
          description: User input
          minLength: 1
        output:
          type: string
          minLength: 0
          description: Command output (mix of stdout & stderr)
        ps1:
          type: string
          description: ps1 (prompt) AFTER the input and output
          minLength: 1
      additionalProperties: false
      required:
        - input
        - output
        - ps1
      examples:
        - input: uptime
          output: '16:37:51 up 19 days,  2:15, 71 users,  load average: 2.01, 2.85, 2.95'
          ps1: user@mindwm-dev1:~/rnd/asyncapi$
    GraphNode:
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - properties:
            type:
              type: string
              enum:
                - created
                - updated
                - deleted
            source:
              type: string
              enum:
                - graph.node
                - graph.relationship
            data:
              allOf:
                - $ref: '#/components/schemas/Neo4jCaptureDataChange'
                - properties:
                    payload:
                      $ref: '#/components/schemas/Neo4jCaptureDataChangeNodePayload'
      additionalProperties: false
      examples:
        - source: graph.node
          subject: IoDocument
          type: created
          id: '5ea0d0c6-4155-11ef-90d8-6f5a5689b5ac'
          specversion: '1.0.0'
          data:
            $ref: '#/components/schemas/Neo4jCaptureDataChangeNodePayload/examples/0'
    GraphRelationship:
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - properties:
            type:
              type: string
              enum:
                - created
                - updated
                - deleted
            source:
              type: string
              enum:
                - graph.relationship
            data:
              allOf:
                - $ref: '#/components/schemas/Neo4jCaptureDataChange'
                - properties:
                    payload:
                      $ref: '#/components/schemas/Neo4jCaptureDataChangeRelationshipPayload'
      additionalProperties: false
      examples:
        - source: graph.relationship
          subject: HAS_IO_DOCUMENT
          type: created
          id: '9f1462e4-9fd4-44f4-9169-d554fba50e85'
          specversion: '1.0.0'
          data:
            $ref: '#/components/schemas/Neo4jCaptureDataChangeRelationshipPayload/examples/0'

    IoDocument:
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - properties:
            type:
              type: string
              const: IoDocument
              default: IoDocument
            subject:
              type: string
              const: IoDocument
              default: IoDocument
            source:
              type: string
              pattern: '[a-zA-Z0-9_][a-zA-Z0-9_-]{0,31}\\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-)\\.tmux\\.[A-Za-z0-9+/]*={0,2}\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.[0-9]+?\\.[0-9]+?\\.iodocument$'
            data:
              $ref: '#/components/schemas/TmuxPaneIoDocument'
      additionalProperties: false
      required: [ subject, source ]
      examples:
        - source: mindwm.alice.laptop.tmux.L3RtcC90bXV4LTEwMDAvZGVmYXVsdA==.1c41f0ca-4056-11ef-a365-5b2236197e08.0.15.iodocument
          subject: IoDocument
          type: IoDocument
          id: '2f3ad8a4-4056-11ef-86f8-9f634df7447b'
          specversion: '1.0.0'
          data:
            $ref: '#/components/schemas/TmuxPaneIoDocument/examples/0'

