name: Two Step Workflow

on:
  push:
    branches:
      - master

jobs:
  generate-and-grep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: KCL run
      uses: addnab/docker-run-action@v3
      with:
        image: kcllang/kcl:v0.9.0
        options: -v ${{ github.workspace }}:/github/workspace
        run: | 
          pwd
          ls
          cd /github/workspace/
          kcl run ./mindwm_asyncapi.k | tee asyncapi.yaml
          kcl run ./mindwm_openapi | tee openapi.yaml
          mkdir -p generated/asyncapi generated/openapi generated/modelina


    - name: Generate
      uses: addnab/docker-run-action@v3
      with:
        image: 
        options: -v ${{ github.workspace }}:/github/workspace
        run: | 
          cd /github/workspace/
          asyncapi config analytics --disable
          asyncapi generate fromTemplate /host/asyncapi.yaml @asyncapi/html-template -o generated/asyncapi/html --force-write
