name: Two Step Workflow

on:
  push:
    paths-ignore:
      - "generated/**"
      - "neomodel/**"
    branches:
      - master

jobs:
  generate-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.MINDWM_TOKEN }} | docker login ghcr.io -u metacoma --password-stdin

    - name: Build and Push io-context-service
      run: |
        docker build -t ghcr.io/mindwm/mindwm-api/mindwm-api:latest .
        docker push ghcr.io/mindwm/mindwm-api/mindwm-api:latest


    - name: Prepare directories
      run: |
        test -d generated && git rm -rf generated
        mkdir -p generated/asyncapi generated/openapi generated/modelina
        chmod a+rwx -R generated

    - name: KCL run
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/mindwm/mindwm-api/mindwm-api:latest
        options: -v ${{ github.workspace }}:/github/workspace
        run: | 
          pwd
          ls
          cd /github/workspace/
          kcl mod update
          kcl run ./mindwm_asyncapi.k | tee generated/asyncapi/asyncapi.yaml
          cp ./cloudevents.json generated/asyncapi/
          kcl run ./mindwm_openapi | tee generated/openapi/openapi.yaml
          GDSCRIPT_WORKAROUND=1 kcl run ./mindwm_openapi | yq 'del(.. | select(has("const")).const)' | tee generated/openapi/openapi_gdscript.yaml
          cp ./cloudevents.json generated/openapi


#    - name: asyncapi html-template generate
#      uses: addnab/docker-run-action@v3
#      with:
#        image: asyncapi/cli:2.0.3
#        options: -v ${{ github.workspace }}:/github/workspace
#        shell: /bin/sh
#        run: | 
#          cd /github/workspace/
#          asyncapi config analytics --disable
#          asyncapi generate fromTemplate generated/asyncapi/asyncapi.yaml @asyncapi/html-template -o generated/asyncapi/html --force-write
#
#    - name: openapi generate
#      uses: addnab/docker-run-action@v3
#      with:
#        image: openapitools/openapi-generator-cli:v7.7.0
#        options: -v ${{ github.workspace }}:/github/workspace
#        shell: /bin/sh
#        run: | 
#          cd /github/workspace/
#          for lang in `docker-entrypoint.sh list -s | sed 's/,/ /g'`; do 
#            docker-entrypoint.sh generate -i generated/openapi/openapi.yaml -p packageName=MindWM -g ${lang} -o generated/openapi/${lang}; 
#          done

    - name: openapi generate gdscript
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/mindwm/openapi-generator/openapi-generator:gdscript
        options: -v ${{ github.workspace }}:/github/workspace
        shell: /bin/sh
        run: | 
          cd /github/workspace/
          docker-entrypoint.sh generate -i generated/openapi/openapi_gdscript.yaml -p packageName=MindWM -g gdscript -o generated/openapi/gdscript; 
          rm -v generated/openapi/openapi_gdscript.yaml

    - name: Commit changes
      run: |
          git add generated

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
        

#    - name: Pushes to another repository
#      id: push_directory
#      uses: cpina/github-action-push-to-another-repository@target-branch
#      env:
#        API_TOKEN_GITHUB: ${{ secrets.MINDWM_TOKEN }}
#      with:
#        source-directory: generated/asyncapi/html
#        destination-github-username: 'mindwm'
#        destination-repository-name: 'mindwm.github.io'
#        user-email: github-actions@github.com
#        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
#        target-branch: main
