name: Two Step Workflow

on:
  push:
    paths-ignore:
      - "generated/**"
    branches:
      - master

jobs:
  generate-and-grep:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare directories
      run: |
        test -d generated && git rm -rf generated
        mkdir -p generated/asyncapi generated/openapi generated/modelina
        chmod a+rwx -R generated

    - name: KCL run
      uses: addnab/docker-run-action@v3
      with:
        image: kcllang/kcl:v0.9.0
        options: -v ${{ github.workspace }}:/github/workspace
        run: | 
          pwd
          ls
          cd /github/workspace/
          kcl mod update
          kcl run ./mindwm_asyncapi.k | tee generated/asyncapi/asyncapi.yaml
          kcl run ./mindwm_openapi | tee generated/openapi/openapi.yaml


    - name: asyncapi html-template generate
      uses: addnab/docker-run-action@v3
      with:
        image: asyncapi/cli:2.0.3
        options: -v ${{ github.workspace }}:/github/workspace
        shell: /bin/sh
        run: | 
          cd /github/workspace/
          asyncapi config analytics --disable
          asyncapi generate fromTemplate ./asyncapi.yaml @asyncapi/html-template -o generated/asyncapi/html --force-write

    - name: openapi generate
      uses: addnab/docker-run-action@v3
      with:
        image: openapitools/openapi-generator-cli:v7.7.0
        options: -v ${{ github.workspace }}:/github/workspace
        shell: /bin/sh
        run: | 
          cd /github/workspace/
          for lang in `docker-entrypoint.sh list -s | sed 's/,/ /g'`; do 
            docker-entrypoint.sh generate -i generated/openapi/openapi.yaml -p packageName=MindwWM -g ${lang} -o generated/${lang}; 
          done

    - name: Commit changes
      run: |
          git add generated

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
        
